version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: .
    container_name: repocanvas_worker
    ports:
      - "8002:8002"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - WORKER_HOST=0.0.0.0
      - WORKER_PORT=8002
    volumes:
      - ./data:/app/data
      - /tmp/repos:/tmp/repos
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
